/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myblockchain;

/**
 *
 * @author user
 */
import java.security.Key;
import java.security.PublicKey;
import java.security.Security;
import java.util.ArrayList;
//import java.util.Base64;
import java.util.HashMap;
//import com.google.gson.GsonBuilder;
import java.util.Map;
import java.util.Scanner;

public class MyCoin extends javax.swing.JFrame {

    
    public MyCoin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        xLbl = new javax.swing.JLabel();
        hyrjeLbl = new javax.swing.JLabel();
        derguesLbl = new javax.swing.JLabel();
        derguesTxtField = new javax.swing.JTextField();
        drgShfaqBaLbl = new javax.swing.JLabel();
        dergBalanc = new javax.swing.JLabel();
        marresLbl = new javax.swing.JLabel();
        marresTxtField = new javax.swing.JTextField();
        marrShfaqBaLbl = new javax.swing.JLabel();
        marrBalanc = new javax.swing.JLabel();
        vleraLbl = new javax.swing.JLabel();
        vleraTxtField = new javax.swing.JTextField();
        dergoButton = new javax.swing.JButton();
        msgLbl = new javax.swing.JLabel();
        txtLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dergBalanceTxtField = new javax.swing.JTextField();
        marrBalanceTxtField = new javax.swing.JTextField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyCoin");
        setFocusTraversalPolicyProvider(true);
        setLocation(new java.awt.Point(400, 50));
        setUndecorated(true);

        jPanel1.setLayout(null);

        xLbl.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        xLbl.setForeground(new java.awt.Color(240, 240, 240));
        xLbl.setText("  X");
        xLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xLblMouseClicked(evt);
            }
        });
        jPanel1.add(xLbl);
        xLbl.setBounds(400, 0, 50, 40);

        hyrjeLbl.setFont(new java.awt.Font("Microsoft Tai Le", 2, 16)); // NOI18N
        hyrjeLbl.setForeground(new java.awt.Color(153, 255, 255));
        hyrjeLbl.setText("Kryeni Transaksione shpejt dhe sigurt...");
        jPanel1.add(hyrjeLbl);
        hyrjeLbl.setBounds(40, 70, 370, 24);

        derguesLbl.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        derguesLbl.setForeground(new java.awt.Color(255, 255, 255));
        derguesLbl.setText("Dërguesi:");
        jPanel1.add(derguesLbl);
        derguesLbl.setBounds(30, 120, 90, 25);

        derguesTxtField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(derguesTxtField);
        derguesTxtField.setBounds(30, 150, 397, 21);

        drgShfaqBaLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        drgShfaqBaLbl.setForeground(new java.awt.Color(255, 255, 255));
        drgShfaqBaLbl.setText("Shfaq Balancën");
        drgShfaqBaLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                drgShfaqBaLblMouseClicked(evt);
            }
        });
        jPanel1.add(drgShfaqBaLbl);
        drgShfaqBaLbl.setBounds(100, 174, 93, 20);

        dergBalanc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dergBalanc.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(dergBalanc);
        dergBalanc.setBounds(220, 174, 90, 20);

        marresLbl.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        marresLbl.setForeground(new java.awt.Color(240, 240, 240));
        marresLbl.setText("Marrësi:");
        jPanel1.add(marresLbl);
        marresLbl.setBounds(30, 210, 90, 25);

        marresTxtField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(marresTxtField);
        marresTxtField.setBounds(30, 240, 397, 21);

        marrShfaqBaLbl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        marrShfaqBaLbl.setForeground(new java.awt.Color(255, 255, 255));
        marrShfaqBaLbl.setText("Shfaq Balancën");
        marrShfaqBaLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                marrShfaqBaLblMouseClicked(evt);
            }
        });
        jPanel1.add(marrShfaqBaLbl);
        marrShfaqBaLbl.setBounds(100, 260, 90, 20);

        marrBalanc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        marrBalanc.setForeground(new java.awt.Color(240, 240, 240));
        jPanel1.add(marrBalanc);
        marrBalanc.setBounds(200, 260, 100, 20);

        vleraLbl.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        vleraLbl.setForeground(new java.awt.Color(240, 240, 240));
        vleraLbl.setText("Vlera në MyCoin:");
        jPanel1.add(vleraLbl);
        vleraLbl.setBounds(30, 300, 150, 30);

        vleraTxtField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(vleraTxtField);
        vleraTxtField.setBounds(30, 330, 150, 21);

        dergoButton.setBackground(new java.awt.Color(255, 255, 255));
        dergoButton.setFont(new java.awt.Font("Microsoft Tai Le", 1, 11)); // NOI18N
        dergoButton.setForeground(new java.awt.Color(0, 0, 102));
        dergoButton.setText("Dërgo");
        dergoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dergoButtonMouseClicked(evt);
            }
        });
        jPanel1.add(dergoButton);
        dergoButton.setBounds(190, 360, 90, 30);

        msgLbl.setBackground(new java.awt.Color(255, 255, 255));
        msgLbl.setFont(new java.awt.Font("Microsoft Tai Le", 3, 12)); // NOI18N
        msgLbl.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(msgLbl);
        msgLbl.setBounds(20, 400, 410, 20);

        txtLabel.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        txtLabel.setForeground(new java.awt.Color(240, 240, 240));
        txtLabel.setText("     BALANCA E RE ");
        jPanel1.add(txtLabel);
        txtLabel.setBounds(140, 440, 170, 25);

        jLabel1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Dërguesi:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 460, 88, 32);

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Marrësi:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(310, 470, 77, 27);

        dergBalanceTxtField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(dergBalanceTxtField);
        dergBalanceTxtField.setBounds(40, 500, 120, 38);

        marrBalanceTxtField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(marrBalanceTxtField);
        marrBalanceTxtField.setBounds(290, 500, 120, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myblockchain/mycoinbg.jpg"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 450, 590);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xLblMouseClicked
        System.exit(0);
    }//GEN-LAST:event_xLblMouseClicked

    private void drgShfaqBaLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drgShfaqBaLblMouseClicked
        String drgCelesPublik = derguesTxtField.getText();
        boolean ndodhet = false;
        for (Portofol p : portofolet) {
            String celesStr = UtiliteteString.getStringNgaCelesi(p.getCelesPublik());
            if(drgCelesPublik.equals(celesStr)){
                dergBalanc.setText(Float.toString(p.getBalance()));
                ndodhet = true;
            }
        }
        if(ndodhet==false){
            msgLbl.setText("Derguesi me kete Celes Publik nuk eshte pjese e ketij blockchain!");
            dergoButton.setEnabled(false);
        }
    }//GEN-LAST:event_drgShfaqBaLblMouseClicked

    private void marrShfaqBaLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marrShfaqBaLblMouseClicked
        String marrCelesPublik = marresTxtField.getText();
        boolean ndodhet = false;
        for (Portofol p : portofolet) {
            String celesStr = UtiliteteString.getStringNgaCelesi(p.getCelesPublik());
            if(marrCelesPublik.equals(celesStr)){
                marrBalanc.setText(Float.toString(p.getBalance()));
                ndodhet = true;
            }
        }
        if(!ndodhet){
            msgLbl.setText("Marresi me kete Celes Publik nuk eshte pjese e ketij blockchain!");
            dergoButton.setEnabled(false);
        }
    }//GEN-LAST:event_marrShfaqBaLblMouseClicked

    private void dergoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dergoButtonMouseClicked
        String drgCelesPublik = derguesTxtField.getText();
        boolean ndodhet = false;
        Portofol dergues=null;
        for (Portofol p : portofolet) {
            String celesStr = UtiliteteString.getStringNgaCelesi(p.getCelesPublik());
            if(drgCelesPublik.equals(celesStr)){
                ndodhet = true;
                dergues=p;
                break;
            }
        }
        if(!ndodhet){
            msgLbl.setText("Derguesi me kete Celes Publik nuk eshte pjese e ketij blockchain!");
        }
        String marrCelesPublik = marresTxtField.getText();
        boolean ndodhet1 = false;
        Portofol marres=null;
        for (Portofol p : portofolet) {
            String celesStr = UtiliteteString.getStringNgaCelesi(p.getCelesPublik());
            if(marrCelesPublik.equals(celesStr)){
                ndodhet1 = true;
                marres=p;
                break;
            }
        }
        if(!ndodhet1){
            msgLbl.setText("Marresi me kete Celes Publik nuk eshte pjese e ketij blockchain!");
            
        }
        
        if(ndodhet1 && ndodhet){
            float vlere = Float.parseFloat(vleraTxtField.getText());
            if(vlere <= minTransaksion ){
                msgLbl.setText("Vlera eshte me e vogel se minimumi: " + minTransaksion);
            }else if( dergues.getBalance() <= vlere){
                msgLbl.setText("Vlera: "+ vlere +" nuk suportohet nga balanca juaj: "+ dergues.getBalance());
            }else{
                String hashPerpara = blockchain.get(blockchain.size()-1).hash;
                Bllok bllokRi = new Bllok(hashPerpara);
                bllokRi.shtoTransaksion(dergues.dergoFonde(marres.celesPublik, vlere));
                shtoBllok(bllokRi);
                msgLbl.setText("Transaksioni u krye me sukes!");
            }

            dergBalanceTxtField.setText(dergues.getBalance()+" MyCoin");
            marrBalanceTxtField.setText(marres.getBalance()+" MyCoin");
        }
    }//GEN-LAST:event_dergoButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyCoin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyCoin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyCoin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyCoin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyCoin().setVisible(true);
                
            }
        });
        		//shtojme blloqet ne ArrayList blockchain:
		Security.addProvider(new org.bouncycastle.jce.provider.BouncyCastleProvider()); //Vnedosim ofruesin e sigurise Bouncey Castle
		
		//Krijome portofolet:
		portofol1 = new Portofol();
		portofol2 = new Portofol();		
		Portofol portofolBaze = new Portofol();
                portofolet.add(portofolBaze);
                portofolet.add(portofol1);
                portofolet.add(portofol2);
                
		
		//Krijojme transaksionin e gjenezes,i cili dergon 100 MyCoin tek portofoli i pare:
		transaksionGjenez = new Transaksion(portofolet.get(0).celesPublik, portofol1.celesPublik, 100f, null);
		transaksionGjenez.gjeneroNenshkrimin(portofolBaze.celesPrivat);	 //Behet nenshkrimi manual i transaksionit te gjenezes	
		transaksionGjenez.transaksionId = "0"; //vendoset id ne menyre manuale
		transaksionGjenez.outputet.add(new TransaksionOutput(transaksionGjenez.marres, transaksionGjenez.vlera, transaksionGjenez.transaksionId)); //shtojme ne menyre manuale output-in e transaksionit
		UTXOs.put(transaksionGjenez.outputet.get(0).id, transaksionGjenez.outputet.get(0)); //ruajme transaksionin tone te pare ne listen e UTXOs.
		
		System.out.println("Krijimi dhe minimi i bllokut te gjenezes... ");
		Bllok gjeneza = new Bllok("0");
		gjeneza.shtoTransaksion(transaksionGjenez);
		shtoBllok(gjeneza);
		
		//testing
		Bllok blloku1 = new Bllok(gjeneza.hash);
		System.out.println("\nBalanca e portofolit 1: " + portofolet.get(1).getBalance());
		System.out.println("\nPortofoli 1 po perpiqet te coje fonde tek Portofoli2(40 MyCoin)...");
		blloku1.shtoTransaksion(portofolet.get(1).dergoFonde(portofolet.get(2).celesPublik, 40f));
		shtoBllok(blloku1);
		System.out.println("\nBalanca e portofolit 1: " + portofol1.getBalance());
		System.out.println("Balanca e portofolit 2: " + portofol2.getBalance());
                
                System.out.println("\n------------------------------------\n");        
                for (int i = 0; i < portofolet.size(); i++) {
                    System.out.println("Celesi i portofolit " + i + " :" + UtiliteteString.getStringNgaCelesi(portofolet.get(i).getCelesPublik()));
                }
		
		eshteZinxhiriValid();
    }
    
    	public static Boolean eshteZinxhiriValid() {
		Bllok bllokuAktual; 
		Bllok bllokPerpara;
		String hashTarget = new String(new char[prefix]).replace('\0', '0');
		HashMap<String,TransaksionOutput> tempUTXOs = new HashMap<String,TransaksionOutput>(); //nje liste e perkoheshme me transaksione te pashpenzuara ne nje gjendje blloku te dhene.
		tempUTXOs.put(transaksionGjenez.outputet.get(0).id, transaksionGjenez.outputet.get(0));
		
		//cikel pergjat blockchain per te kontrolluar hashet:
		for(int i=1; i < blockchain.size(); i++) {
			
			bllokuAktual = blockchain.get(i);
			bllokPerpara = blockchain.get(i-1);
			//krahaso hashin e regjistruar me ate te llogariturin:
			if(!bllokuAktual.hash.equals(bllokuAktual.llogaritHash()) ){
				System.out.println("#Hashet Aktuale nuk jane te barabarta");
				return false;
			}
			//krahaso hashin e llogarit te bllokut para me hashin e meperparshem te bllokut aktual  
			if(!bllokPerpara.hash.equals(bllokuAktual.hashPerpara) ) {
				System.out.println("#Hashet e meperpareshme nuk jane te barabarta");
				return false;
			}
			//kontrollo nese hashi eshte zgjidhur/minuar
			if(!bllokuAktual.hash.substring(0, prefix).equals(hashTarget)) {
				System.out.println("#Hashi nuk eshte minuar");
				return false;
			}
			
			//cikel pergjate transaksioneve te blockchain:
			TransaksionOutput tempOutput;
			for(int t=0; t <bllokuAktual.transaksione.size(); t++) {
				Transaksion transaksionAktual = bllokuAktual.transaksione.get(t);
				
				if(!transaksionAktual.verifikoNenshkrimin()) {
					System.out.println("#Nenshkrimi ne transaksionin (" + t + ") nuk eshte i vlefshem");
					return false; 
				}
				if(transaksionAktual.getVleraInputeve() != transaksionAktual.getVleraOutputeve()) {
					System.out.println("#Inputet nuk jane te barabarta me outputet ne transaksionin(" + t + ")");
					return false; 
				}
				
				for(TransaksionInput input: transaksionAktual.inputet) {	
					tempOutput = tempUTXOs.get(input.treansaksionOutputId);
					
					if(tempOutput == null) {
						System.out.println("#Inputi i referencuar ne Transaksionin (" + t + ") mungon!");
						return false;
					}
					
					if(input.UTXO.vlera != tempOutput.vlera) {
						System.out.println("#Inputi i referencuar ne Transaksionin (" + t + ") ka vlere te pavlefshme!");
						return false;
					}
					
					tempUTXOs.remove(input.treansaksionOutputId);
				}
				
				for(TransaksionOutput output: transaksionAktual.outputet) {
					tempUTXOs.put(output.id, output);
				}
				
				if( transaksionAktual.outputet.get(0).marresi != transaksionAktual.marres) {
					System.out.println("#Marresi i outputit te transaksionit (" + t + ") nuk eshte marresi ne fjale!");
					return false;
				}
				if( transaksionAktual.outputet.get(1).marresi != transaksionAktual.dergues) {
					System.out.println("#Mbetja e transaksionit (" + t + ") nuk po i kthehet derguesit!");
					return false;
				}
				
			}
			
		}
		System.out.println("Blockchain eshte i vlefshem");
		return true;
	}
	
	public static void shtoBllok(Bllok bllokRi) {
		bllokRi.minoBllokun(prefix);
		blockchain.add(bllokRi);
	}

    public static ArrayList<Bllok> blockchain = new ArrayList<Bllok>();
    public static HashMap<String,TransaksionOutput> UTXOs = new HashMap<String,TransaksionOutput>();
    public static ArrayList<Portofol> portofolet = new ArrayList<Portofol>();
	
    public static int prefix = 3;
    public static float minTransaksion = 0.1f;
    public static Portofol portofol1;
    public static Portofol portofol2;
    public static Transaksion transaksionGjenez;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel dergBalanc;
    private javax.swing.JTextField dergBalanceTxtField;
    private javax.swing.JButton dergoButton;
    private javax.swing.JLabel derguesLbl;
    private javax.swing.JTextField derguesTxtField;
    private javax.swing.JLabel drgShfaqBaLbl;
    private javax.swing.JLabel hyrjeLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel marrBalanc;
    private javax.swing.JTextField marrBalanceTxtField;
    private javax.swing.JLabel marrShfaqBaLbl;
    private javax.swing.JLabel marresLbl;
    private javax.swing.JTextField marresTxtField;
    private javax.swing.JLabel msgLbl;
    private javax.swing.JLabel txtLabel;
    private javax.swing.JLabel vleraLbl;
    private javax.swing.JTextField vleraTxtField;
    private javax.swing.JLabel xLbl;
    // End of variables declaration//GEN-END:variables
}
